# Generated by Django 5.0.1 on 2026-01-30 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The main question being asked in the poll",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional detailed description of the poll",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this poll is currently accepting votes",
                    ),
                ),
                (
                    "allow_multiple_votes",
                    models.BooleanField(
                        default=False,
                        help_text="Allow users to vote multiple times on this poll",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this poll was created"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this poll stops accepting votes (optional)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this poll (optional for anonymous polls)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="The text of this option/choice", max_length=200
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order of this option"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poll",
                    models.ForeignKey(
                        help_text="The poll this option belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="polls.poll",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index", "id"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voter_identifier",
                    models.CharField(
                        help_text="IP address or user ID to prevent duplicate votes",
                        max_length=255,
                    ),
                ),
                (
                    "voted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this vote was cast"
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        help_text="The option that was voted for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.option",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        help_text="The poll this vote belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.poll",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["is_active"], name="polls_poll_is_acti_53c655_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["expires_at"], name="polls_poll_expires_0c4433_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["-created_at"], name="polls_poll_created_fdd0dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="option",
            index=models.Index(fields=["poll"], name="polls_optio_poll_id_70539b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="option",
            unique_together={("poll", "order_index")},
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["poll", "voter_identifier"],
                name="polls_vote_poll_id_181ab3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["option"], name="polls_vote_option__9fc1fb_idx"),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("poll", "voter_identifier"),
                name="unique_vote_per_poll",
                violation_error_message="You have already voted on this poll",
            ),
        ),
    ]
