from django.urls import path, include
from res_framework.routers import DefaultRouter
from .views import UserRegistrationView, UserProfileView, PollViewSet


# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'polls', PollViewSet, basename='poll')

urlpatterns = [
    #Aunthentication endpoints
    path('auth/register/', UserRegistrationView.as_view(), name='user-register'),
    path('auth/profile/', UserProfileView.as_view(), name='user-profile'),
    
    # Poll endpoints (automatically generated by router)
    path('', include(router.urls)),
]